---
title: "Habituation Data - Background and Analysis Notes"
author: "Laura Brubaker-Wittman"
date: "10/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Background

This project investigate the process of habituation in Bornean orangutans in Gunung Palung National Park in West Kalimantan, Borneo, Indonesia. Specifically, it explores questions regarding orangutan behaviors during habituation, viewing these as strategies employed by the orangutan to evade humans until they become more habituated to our presence. These strategies include *hiding,* *vocalizing,* and *traveling.* Specifically, we look at the differences in these strategies between age-sex classes (e.g. ung=flanged males, adolescent females, etc.), and in the presence of offspring or other conspecifics. Furthermore, these strategies employ different levels of energy expenditure (i.e. traveling is more energetically costly than hiding). We explore if fruit availability at the time of habituation impacts which strategy is employed by orangutans, as part of a trade off decision as proposed by life history theory.

## Research Questions

This research asks the following questions:

1. Can we determine, based on percentage of time spent in specific activities and behaviors, if orangutans are habituated or not?
2. Is there a difference in strategies employed by the various age-sex classes?
3. Do mothers with offspring employ different strategies than when they are without offspring?
4. Does the presence of conspecifics that are not offspring impact which strategy is used?
5. Does fruit availability impact the strategy employed?

## Sub-sampling Data and Exclusion Criteria
